### ISSUE TITLE
convnext_large_d_320_CocoPanopticOVDataset.pth

### ISSUE THREAD

**Issue by Reginald-L** [lxtGH/OMG-Seg#1]
when I run the code, I got an error: FileNotFoundError: 
[Errno 2] No such file or directory: '/home/myname/.cache/embd/convnext_large_d_320_CocoPanopticOVDataset.pth', but I can  not find this pth file on huggingface and timm, may I get any help?

thanks very much

**Comment by lxtGH** [comment]
Hi! We are still adding the inference demo and updating ReadMe. Please stay tuned.

**Comment by lxtGH** [comment]
We have update the code and please have a try

**Comment by ArtemSivtsov** [comment]
Hi @lxtGH ! 

I face similar issue when attempting to start test.py for CityScapes dataset. It says: `FileNotFoundError: [Errno 2] No such file or directory: '/home/aa_siv/.cache/embd/convnext_large_d_320_CityscapesPanopticDataset.pth'`

Is there any hope for update connected with that error too? :)

**Comment by lxtGH** [comment]
Please see the latest file of generating the [embedding](https://github.com/lxtGH/OMG-Seg/blob/main/EMB.md).
