### ISSUE TITLE
Questions about Multi-Dataset Setting

### ISSUE THREAD

**Issue by JiajiaLi04** [lxtGH/OMG-Seg#10]
Hello, thank you so much for your excellent work. I would like to try to train/fine-tune the model based on our customized data. However, I do not have all of these dataset you introduced in DATASET.md. Can I just use a few of them to train the model? For example, I only have coco-format data(only for instance segmentation, not for panoptic seg), and cityscape format data. Is it possible to directly use your training codes?  Thank you. Looking forward to your reply.

**Comment by lxtGH** [comment]
@JiajiaLi04 Hi! Thanks for your question, I will add one tutorial in the end of this month.

**Comment by JiajiaLi04** [comment]
Thank you. Looking forward to your updates.

**Comment by lxtGH** [comment]
@JiajiaLi04 Please check the demo folder.

**Comment by lxtGH** [comment]
@hustdonk 直接参考下coco dataset的格式，把对应的json替换，以及重新生成下class name的embedding。
