### ISSUE TITLE
clip backbone missing

### ISSUE THREAD

**Issue by Yonggie** [lxtGH/OMG-Seg#11]
Readme "this script will help download the clip backbone” does not lead to any valid link. Unaware of the type of clip backbone

**Comment by lxtGH** [comment]
Hard to understand your comments. Please show the error to us.

**Comment by lxtGH** [comment]
I test the current version in my local machine. It can download the pre-trained CLIP backbone.

**Comment by Yonggie** [comment]
Hi, thx for the reply. I mean in the readme description, there is the link missing.
![图片](https://github.com/lxtGH/OMG-Seg/assets/31330044/867b5813-e6f7-4fcd-9dea-5014aabac568)

**Comment by HarborYuan** [comment]
The script means train or test script. CLIP checkpoints will be automatically downloaded.

**Comment by Yonggie** [comment]
got it
