### ISSUE TITLE
How to export to ONNX

### ISSUE THREAD

**Issue by anhquannguyen21** [lxtGH/OMG-Seg#14]
Thank you for great work @lxtGH.
 How to export OMG-SEG model to onnx, can you give me a guide?

**Comment by lxtGH** [comment]
@anhquannguyen21 Sorry. We currently do not support such features.

**Comment by lxtGH** [comment]
https://mmdetection.readthedocs.io/en/v2.13.0/tutorials/pytorch2onnx.html

Maybe this doc help.
