### ISSUE TITLE
Env Installing Error

### ISSUE THREAD

**Issue by dddraxxx** [lxtGH/OMG-Seg#17]
Thanks for the great repo. I want to mention that when installing mmcv, I need to do this
```
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
TORCH_CUDA_ARCH_LIST="8.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" CUDA_HOME=$(dirname $(dirname $(which nvcc))) MMCV_WITH_OPS=1 FORCE_CUDA=1 python -m pip install git+https://github.com/open-mmlab/mmcv.git@4f65f91db6502d990ce2ee5de0337441fb69dd10
```
instead of `TORCH_CUDA_ARCH_LIST="8.0" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" CUDA_HOME=$(dirname $(dirname $(which nvcc))) LD_LIBRARY_PATH=$(dirname $(dirname $(which nvcc)))/lib MMCV_WITH_OPS=1 FORCE_CUDA=1 python -m pip install git+https://github.com/open-mmlab/mmcv.git@4f65f91db6502d990ce2ee5de0337441fb69dd10` to prevent the line from raising error about compiler CUDA version not the same as torch.

**Comment by lxtGH** [comment]
Hi! I have updated the readme. Make sure your mmcv to align with your torch version and make sure mmdet == v.3.1.0

See the doc here. https://mmcv.readthedocs.io/en/latest/get_started/installation.html
