### ISSUE TITLE
test on one image

### ISSUE THREAD

**Issue by hcscysh** [lxtGH/OMG-Seg#20]
Your work is perfect.How can I test image with a easy way?such as in test.py,I only need to supply a image path, load the modek and the result is calculated.

**Comment by lxtGH** [comment]
@hcscysh Thanks for your suggestion. The simple test.py and easy to use scripts will be provided by the weekend. 
Please stay tuned.

**Comment by hcscysh** [comment]
Thanks for your reply.
I will always pay attention to you.

**Comment by VoyagerXvoyagerx** [comment]
Thanks for your novel work, a simple `inference.py` would be better for beginners. (`test.py` is used to evaluate the whole dataset, while inference.py just calculate the result. )

**Comment by lxtGH** [comment]
Hi! Guys, Please check the demo folder for easier usage of pre-trained model. Thanks！
