### ISSUE TITLE
Why does this error occur when I run test.py

### ISSUE THREAD

**Issue by xihao-1223** [lxtGH/OMG-Seg#21]
![image](https://github.com/user-attachments/assets/a4b3118a-1b88-408b-8825-7e7b3132ae20)

**Comment by xihao-1223** [comment]
![image](https://github.com/user-attachments/assets/c886080a-16b9-451b-87a1-dc2d833e25d7)


This problem occurs when loading norm_layer.

**Comment by hcscysh** [comment]
I also meet the question.I sloved it by installing the highest version of mmcv that conda environment allowed.

**Comment by xihao-1223** [comment]
Is it the same error? The get method gets a nn.Module instead of a string. Could you provide the version information you installed? I am now fully aligning the environment information provided on git. If this still doesn't solve the problem, I would like to try your method.

**Comment by hcscysh** [comment]
from the error information,we are the same error.The mmcv vision from 2.2 to downgrade 2.0.1 solved my error.The following is my environment.
mmengine: 0.8.5
mmcv: 2.0.1
mmdet: 3.1.0
torch: 1.13.1+cu117

**Comment by lxtGH** [comment]
@xihao-1223 Hi， which file and comand line do you run?
