### ISSUE TITLE
Questions about the code

### ISSUE THREAD

**Issue by chunshengshi** [lxtGH/OMG-Seg#24]
In the omg_llava_collate_fn.py file, there is a problem with attention_mask[:i] = True. I think it should be attention_mask[:,:i] = True. Hope that answers, thanks!

**Comment by lxtGH** [comment]
@zhang-tao-whu Please check this issue. It seems a bug from xtuner.

**Comment by zhang-tao-whu** [comment]
Thank you very much for your discovery. This is a bug from the xtuner library. After fixing this bug, we attempted retraining, and there was a little performance improvement. For example, the cIoU on refCOCO val without finetuning increased from 65.6 to 66.3.
