### ISSUE TITLE
convnext_large_d_320_th139_st101.pth

### ISSUE THREAD

**Issue by hcscysh** [lxtGH/OMG-Seg#26]
In the images_demo.py, how to get the convnext_large_d_320_th139_st101.pth,I can't find it in the embedding!

**Comment by HarborYuan** [comment]
Hi @hcscysh ,

Thanks for your interest.
You need to generate the `convnext_large_d_320_th139_st101.pth` by yourself. You can generate the embedding file by:
```
PYTHONPATH=. python tools/gen_cls.py demo/configs/m2_convl.py
```

The script will automatically read the class names in 
```
demo/configs/names/th139_st101.py
```
to generate the embedding.

Please let me know if you have any other questions.
