### ISSUE TITLE
A bug with size mismatch

### ISSUE THREAD

**Issue by Butingg** [lxtGH/OMG-Seg#30]
size mismatch for llm.base_model.model.model.tok_embeddings.weight: copying a param with shape torch.Size([92548, 4096]) from checkpoint, the shape in current model is torch.Size([92554, 4096]).
size mismatch for llm.base_model.model.output.base_layer.weight: copying a param with shape torch.Size([92548, 4096]) from checkpoint, the shape in current model is torch.Size([92554, 4096]).
size mismatch for llm.base_model.model.output.lora_B.default.weight: copying a param with shape torch.Size([92548, 512]) from checkpoint, the shape in current model is torch.Size([92554, 512]).

The parameter dimension does not match. It should be 92548, but the model is 92554.

**Comment by lxtGH** [comment]
@Butingg This is transformers version problem. Please check your transformers version.

**Comment by zhang-tao-whu** [comment]
Loading a checkpoint trained with a lower version of transformers using a higher version of transformers can cause this bug. You can downgrade the transformers version to 4.36.0 to load the checkpoint we provided, or retrain using a higher version of transformers such as 4.42.0.
