### ISSUE TITLE
A terrible repository and demo

### ISSUE THREAD

**Issue by YuetKaka15** [lxtGH/OMG-Seg#33]
A terrible repository and demo

**Comment by zhang-tao-whu** [comment]
We apologize, but due to insufficient resources, we are unable to deploy a long-term online demo. However, if you need, you can run a local Gradio demo by following the instructions in the README.

**Comment by lxtGH** [comment]
@YuetKaka15 You are welcome to give some suggestions to make the repo easy to use since the model and datasets are complex and have lots of engineering efforts.
