### ISSUE TITLE
How to check the model result of OMG-LlaVa on a given image?

### ISSUE THREAD

**Issue by placeforyiming** [lxtGH/OMG-Seg#34]
I have already downloaded the weights from the HuggingFace and prepare the environment by following the instruction here: https://github.com/lxtGH/OMG-Seg/blob/main/omg_llava/INSTALL.md

Then, which command or script should I run for testing a given image? Let's say, the image path is : https://github.com/lxtGH/OMG-Seg/blob/main/omg_llava/test.jpg

**Comment by lxtGH** [comment]
@placeforyiming Thanks for your question. We will provide a jupter notebook soon.

**Comment by aimll101** [comment]
> @placeforyiming Thanks for your question. We will provide a jupter notebook soon.
How long will it take approximately?

**Comment by aimll101** [comment]
@lxtGH How long will it take approximately?

**Comment by placeforyiming** [comment]
The gradio example works for me
