### ISSUE TITLE
Multi node training?

### ISSUE THREAD

**Issue by echo840** [lxtGH/OMG-Seg#35]
Does this code support multi-machine training, and how should I modify the training command?

**Comment by HarborYuan** [comment]
You do not need to modify the code. If you are using Slurm, you should use this script:
> https://github.com/lxtGH/OMG-Seg/blob/main/tools/slurm.sh


Else you are expected to use this:
> https://github.com/lxtGH/OMG-Seg/blob/main/tools/dist.sh

In this case, you need to set the `MASTER_ADDR `, `PORT `, `NODE_RANK `, `NNODES `, and `GPUS` by yourself.
