### ISSUE TITLE
When I train,an error occur

### ISSUE THREAD

**Issue by aimll101** [lxtGH/OMG-Seg#36]
command:PYTHONPATH=. NPROC_PER_NODE=8 xtuner train     omg_llava/configs/finetune/specific_tasks_finetune/finetune_refseg.py     --deepspeed deepspeed_zero2
![微信图片_20240823203859](https://github.com/user-attachments/assets/79a98502-7f6c-46b2-98f6-9eecd046cd77)

**Comment by lxtGH** [comment]
@zhang-tao-whu Please see this problem.
