### ISSUE TITLE
When I test,aTypeError occur.

### ISSUE THREAD

**Issue by aimll101** [lxtGH/OMG-Seg#38]
Could you please help solve the following problem?
command:PYTHONPATH=. NPROC_PER_NODE=8 xtuner test     omg_llava/configs/finetune/specific_tasks_finetune/finetune_refseg.py 
![image](https://github.com/user-attachments/assets/64f70d5b-6c2d-4ebe-a809-d4467b9e6d72)

**Comment by zhang-tao-whu** [comment]
Please refer to the (README.md)[https://github.com/lxtGH/OMG-Seg/blob/main/omg_llava/README.md]. The test command is ```# for evaluation referring expression segmentation
NPROC_PER_NODE=8 xtuner refcoco_omg_seg_llava \
  ${PATH_TO_CONFIG} \
  ${PATH_TO_PTH} \
  --dataset ${refcoco or refcoco_plus or refcocog} \
  --split ${val or testA or testB}```
