### ISSUE TITLE
about inference code open source？

### ISSUE THREAD

**Issue by QzYER** [lxtGH/OMG-Seg#4]
Thank you for the author's open-source work. The article mentioned that the reasoning process is the same as mask2former. Has the author open-source reasoning code based on different segmentation tasks? Looking forward to your reply

**Comment by shohmax** [comment]
Hi, how about the inference speed compared to SAM?

**Comment by lxtGH** [comment]
@shohmax Hi! We do not compare with SAM on inference speed. For GFlops, our model is smaller.
