### ISSUE TITLE
demo is not work

### ISSUE THREAD

**Issue by liyaowei-stu** [lxtGH/OMG-Seg#46]
image_demo is not work.
![test_img](https://github.com/user-attachments/assets/6a5335d0-f43b-4635-a631-32b2ba957108)

**Comment by liyaowei-stu** [comment]
![image](https://github.com/user-attachments/assets/2683d8ea-cc30-4b0b-bc6a-b621c37b974c)

**Comment by liyaowei-stu** [comment]
I reinstalled the mmcv environment and solved this problem.

**Comment by liyaowei-stu** [comment]
I reinstalled the mmcv environment and solved this problem.

**Comment by liyaowei-stu** [comment]
I reinstalled the mmcv environment and solved this problem.

**Comment by DQiaole** [comment]
> I reinstalled the mmcv environment and solved this problem.

Hi, I get a similar result as yours. But reinstalling the mmcv cannot solve the problem. Could you provide more detials on how to solve this? Thank you very much.

**Comment by GustavoStahl** [comment]
To help anyone who might run into this error, here's how I set up my `conda` environment to get the demo code working properly:

1. Create the environment and install PyTorch
```bash
conda create -n omg-seg python=3.10
conda activate omg-seg
conda install pytorch==2.0.1 torchvision==0.15.2 pytorch-cuda=11.8 -c pytorch -c nvidia
```
2. Install MM libraries
```bash
pip install -U openmim
mim install mmcv==2.0.1 mmengine==0.8.5 mmdet==3.1.0 mmsegmentation==1.1.1 mmpretrain==1.0.1
```
3. Install the remaining libraries
```bash
python -m pip install git+https://github.com/cocodataset/panopticapi.git \
                      git+https://github.com/HarborYuan/lvis-api.git \
                      tqdm terminaltables pycocotools scipy tqdm ftfy regex timm scikit-image kornia
```
4. Fix dependency issues
```bash
pip install "numpy<2" opencv-python==4.8.1.78
```
5. Done! Once you run the demo, you should get an output image like this:

![Image](https://github.com/user-attachments/assets/1e4f7ac6-e2fb-4d4c-9dcd-63acccf1e22b)
