### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by SecretMG** [lxtGH/OMG-Seg#47]
Thanks for your excellent work!

I‘ve installed the env with mmcv==2.0.0 and mmdet==3.1.0, but I got an TypeError when I run the command "PYTHONPATH=. python demo/image_demo.py"

The TypeError is "TypeError: The key argument of `Registry.get` must be a str, got <class 'type'>".

Is the version of mmcv I installed incorrect?

**Comment by HarborYuan** [comment]
Yes, you need to update your mmcv to support using the python type rather than str in the config file.

Please let me know if you have any other questions.
