### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by hcscysh** [lxtGH/OMG-Seg#49]
The work is great,I use it to segment small objects performs well.I want to convert it to onnx,that can deploy on c++,but the preprocess including the mmcv and mmdet,it is a little difficulty . Can you supply a easy to convert the pt to onnx, including the data preprocess and post-processing? Thank you

**Comment by lxtGH** [comment]
Hi! @hcscysh Thanks for your questions, since we use mmdet and mmcv. 

I suggest you to use mmdeploy tool for onnx deployment, https://github.com/open-mmlab/mmdeploy.

Make sure to use the corresponding version.
