### ISSUE TITLE
how to do inference on video or realtime ?

### ISSUE THREAD

**Issue by Ahmed471996** [lxtGH/OMG-Seg#5]
is there a guide on how to use the provided models to infere on videos ?

**Comment by lxtGH** [comment]
@Ahmed471996 Hi! Thanks for your suggestion. I will provide the demo scripts in this week.

**Comment by lxtGH** [comment]
Hi! I have updated the README. Please use the option --show-dir to visualize final results.

**Comment by bankxi** [comment]
Hi! Is there any code for inferring local images/videos
