### ISSUE TITLE
Where is “convnext_large_d_320” in video_demo?

### ISSUE THREAD

**Issue by lianhh1212** [lxtGH/OMG-Seg#56]
Thanks for your great work!
I cannot connect huggingface when i use video_demo for inference. But there needs "convnext_large_d_320" for video_demo. Where can I get "convnext_large_d_320"?  And how do I configure it?

**Comment by lianhh1212** [comment]
解决了

**Comment by 12314312** [comment]
我也碰到了同样的问题，你是怎么解决的？
