### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by yahooo-m** [lxtGH/OMG-Seg#8]
Hi, I noticed that you used 32 A100 GPUs for training in your paper. If I only have V100 GPUs, can I replicate the results?

**Comment by lxtGH** [comment]
@yahooo-m  Thanks for your question. I believe you can try to reproduce the results since I do not use the bs=8 for training.

**Comment by lxtGH** [comment]
Hi! We have re-trained OMG-Seg with only one A100 40G machine. **We obtain the similar results.** I have updated README for reference. For example, we can still obtain 53.5 PQ on COCO without Object-365 pre-training.

**Comment by yahooo-m** [comment]
Thanks! I just noticed the response. I will provide the results~
