### ISSUE TITLE
multi-label for each point

### ISSUE THREAD

**Issue by suliangxu** [lxtGH/OMG-Seg#9]
Thank you for your excellent work! Can OMG-seg predict multi-class for each point? For the human parsing task, we need to segment not only the instance of one person but also the partition of him/her (such as the watch, head, upper body, shoes, and so on). Additionally, how can I fine-tune OMG-seg for such a task? Thank you.

![image](https://github.com/lxtGH/OMG-Seg/assets/50627460/a9055cf5-47eb-4cb2-9dc3-6e6e72859e71)

**Comment by lxtGH** [comment]
Hi! @suliangxu Seems like this is an instance part-aware segmentation task. You can refer to these work for your reference. 

https://github.com/lxtGH/Panoptic-PartFormer

https://github.com/soeaver/awesome-human-parsing

**Comment by suliangxu** [comment]
@lxtGH Thank you for your reply! Another question: how can I test the model for a single image? For example, I can directly specify the path of the image in test.py.

**Comment by lxtGH** [comment]
@suliangxu Please wait for a well. I will add one folder on how to use these models.

**Comment by lxtGH** [comment]
Please check the demo folder.
